name: Mechanic Shop CI/CD

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependenices
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print Debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory $(pwd)"
          echo "Contents of Working Directory: $(ls-l)"
          echo "Contents of site-packages: $(ls-l venv/lib/python*/site-packages)"

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependenices
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests -p 'test_*.py'

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependenices
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID}}
          api-key: ${{ secrets.RENDER_API_KEY}}


      